### ISSUE TITLE
No card type configured

### ISSUE THREAD

**Issue by CumpsD** [gerardag/person-entity-card#11]
**Describe the bug**

Installed via HACS, restarted HA, copy pasted the example and getting `No card type configured`

**To Reproduce**

* Installed via HACS
* Restarted HA
* Copied the example
* Reloaded the browser
* Restarted HA

**Expected behavior**

A working card :)

**Screenshots**

![image](https://user-images.githubusercontent.com/1201644/141464492-c0ebfa9f-0462-4f8e-92e2-74e345104662.png)

![image](https://user-images.githubusercontent.com/1201644/141464528-5d2eabcc-dc07-4547-8726-f4f8504b784f.png)

## System Health

version | core-2021.11.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.78-v7l+
arch | armv7l
timezone | Europe/Brussels

**Comment by gerardag** [comment]
Hi @CumpsD,

I'm pretty sure that you had done, but can you try to reload resources from your view? Sometimes have worked for me with some added plugins.

Although, I'm going to check that everthing is working properly.

**Comment by CumpsD** [comment]
What do you mean exactly with reload from view?

**Comment by gerardag** [comment]
I mean that option on the top right menu

![Uploading 40289DF3-E1FC-4F40-8016-C7AA244A2981.jpeg…]()

**Comment by gerardag** [comment]
I mean the option on the top right corner menu

![image](https://user-images.githubusercontent.com/2340397/141532553-68ddbc7b-3f09-4057-ba39-99cc7578666b.jpeg)

**Comment by CumpsD** [comment]
Interesting, I dont have that:

![image](https://user-images.githubusercontent.com/1201644/141533283-edfcec78-9940-4118-8822-3844e9a7c02f.png)

**Comment by CumpsD** [comment]
Apparently this option is only visible when you use `yaml` for the lovelace dashboard. I'm using the regular editor.

**Comment by CumpsD** [comment]
It does seem to get loaded in the browser:

![image](https://user-images.githubusercontent.com/1201644/141534518-f5b62361-48ce-446d-8cec-16eac7d9afe5.png)

**Comment by CumpsD** [comment]
Found it....

Why it didn't work, I copied the code from the README https://github.com/gerardag/person-entity-card#example-usage

```
- type: "custom:person-entity-card"
  entities:
    - person.gerard
    - person.bar
    - person.foo
```

Which didn't work, but when I changed the indenting to this it works:

```
type: "custom:person-entity-card"
entities:
  - person.gerard
  - person.bar
  - person.foo
```

**Comment by gerardag** [comment]
I'm hapoy you can solved. I'm going to try to replicate your problem. Thanks for the feedback.

**Comment by davidlb** [comment]
I got the same problem, solved by removing dash and indentation.
Thanks!
