### ISSUE TITLE
Status not shown anymore

### ISSUE THREAD

**Issue by marcis92** [gerardag/person-entity-card#35]
**Describe the bug**
For some reason the person entity card doesnt show the current status anymore since I think HA 2023.4.2. See attached screenshot below.
I already reconnected the actual devices and controlled that location permission are active.
However, for example the mushroom person card is still showing the status as expected.

**Expected behavior**
Showing the status again like expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/76939141/231910674-133d1828-991f-47c9-b9a1-92f8df553595.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Edge, Home Assistant Win11 App
 - Version: Chrome: 111.0.5563.147

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: Android 13
 - Browser: Chrome, Companion App

**Additional context**
Code used in the screenshot, mushroom excluded:
```
type: custom:person-entity-card
showAtHome: true
centered: true
entities:
  - person.marcel
  - person.sandra
```

**Comment by GuyKh** [comment]
:+1

**Comment by alanpaone** [comment]
I'm in a zone with a name, and that does show, but my roommates all just use the wifi-based presence, and mine also doesn't show if I'm home or away. maybe something changed with the home and away statuses?
![Screenshot_20230417-152350](https://user-images.githubusercontent.com/10714707/232614016-242ff482-2bed-4451-9624-077debca2176.png)

**Comment by GuyKh** [comment]
I think I've found the problem (#36)

**Comment by mdeluca1992** [comment]
Still seeing this issue. Has the fix been implemented yet?

**Comment by GuyKh** [comment]
@mdeluca1992 - yep -- I have no merging rights so I'm waiting for @gerardag to do that

**Comment by marcis92** [comment]
Hi @gerardag, just saw you merged the fix. Unfortunately there is no updated release. Any chance to push this?

**Comment by alanpaone** [comment]
it looks like when the fix was merged, it should've released automatically, but the [action failed](https://github.com/gerardag/person-entity-card/actions/runs/5196613032), i could be wrong, i am not familiar with github actions
