### ISSUE TITLE
Feature request number columns | align columns

### ISSUE THREAD

**Issue by dannymertens** [gerardag/person-entity-card#8]
Hi,
Great card, is it possible to define the number of columns and/or align them in the card, looks a bit off now

![image](https://user-images.githubusercontent.com/46963011/141119975-8e473810-0b6a-4c0f-98b1-5567a35c2ad5.png)

Thanks in advance and for the great card!

Kind regards

**Comment by gerardag** [comment]
Hello @dannymertens ,
First of all thanks for your feedback, I really apreciate that.

I've updated the library with the "centered" option (check readme for more deailts) which allows to center content (both title and chips) inside the ha-card container.

If you need more options you can use the card-mod (also available in HACS) which allows you to add custom css on every card of your lovelace. I use a lot in many of my cards.

Thanks and I hope this change solve you some problems with card :)
